name: pontoaponto
description: "Projeto Ponto A Ponto."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  geolocator: ^11.1.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.3
  hive: ^2.2.3
  intl: ^0.19.0
  permission_handler: ^11.3.1
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env